### PR TITLE
chore: add support for globs

### LINKED ISSUE #46: Support glob/pattern lint (e.g. bpmnlint **/*.bpmn)
__Is your feature request related to a problem? Please describe__

Hi !

First, thank you for this great tool ! 

We were trying to integrate it on our project, but we had some difficulties to make it work in a npm script, because it doesn't seems to support glob/pattern search.

For instance, when creating a script `npm run check-bpmn`, I got this kind of error:

```
bpmnlint src/**/*.bpmn

Error: Failed to read src/**/*.bpmn
```

__Describe the solution you'd like__

I would like to propose supporting glob search.

__Describe alternatives you've considered__

I think that otherwise, we'll try to implement a wrapper that will give us the same functionnality

### PR DESCRIPTION
**Pull request by clementdessoude**
__Which issue does this PR address?__

I propose this PR to address the issue I raised about glob search. 

It uses the fast-glob libray that can be found here: https://github.com/mrmlnc/fast-glob

It is the same library as Prettier for retrieving matching files: https://github.com/prettier/prettier/blob/86ad2997685a9ac86617502531e9d203976d23ea/src/cli/expand-patterns.js

Closes #46

__Acceptance Criteria__

N/A

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/.github/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
We'd need a [test case](https://github.com/bpmn-io/bpmnlint/blob/master/test/integration/cli-spec.js) to verify this works, cross platform.

**Comment by clementdessoude** [comment]
Hi @nikku !

I added some test, and tried to modify the Travis configuration to add builds on mac and windows. I have to admit I do not understand why it didn't launch the Travis CI on my last commit, do you have an idea ?

**Comment by nikku** [comment]
> I have to admit I do not understand why it didn't launch the Travis CI on my last commit, do you have an idea ?

Likely travis does not allow external contributors to fiddle around with the CI configuration. 

Extracted the CI update to https://github.com/bpmn-io/bpmnlint/pull/48. Makes sure to have CI on all these environments before merging the globbing support.

**Comment by nikku** [comment]
Apparently we ran out of "credits" with our TravisCI account. Despite being on a paid plan, depite having paid extra for additional credits. We'll need to resolve this. 

Thanks in advance already for your PR. We'll merge it, eventually :wink:.

**Comment by nikku** [comment]
Merged via https://github.com/bpmn-io/bpmnlint/commit/23c26a3ca6d41164c5febe108c8f5519b4f90f4f without the CI changes.

**Comment by nikku** [comment]
Ended up using tiny-glob rather than fast-glob for speed and size reasons.

**Comment by clementdessoude** [comment]
Great news!

**Pull request closed without merging**
