### PR TITLE
Add explanation to no-inclusive-gateway rule

### LINKED ISSUE #44: Document `no-inclusive-gateway` rule
__Is your feature request related to a problem? Please describe__

Currently, `no-inclusive-gateway` is a rule in the recommended set. However, the documentation does not give grounds why this element should be disallowed. I couldn't find any sources which would discourage usage of this gateway. This has already caused confusion on [Camunda forum](https://forum.camunda.org/t/linter-plugin-error-element-has-disallowed-type-bpmn-inclusivegateway/23320).

__Describe the solution you'd like__

Add grounds why rule exists and should be used.

__Describe alternatives you've considered__

Remove the rule from the recommended set, but it has already been decided against in https://github.com/bpmn-io/bpmnlint/issues/41#issuecomment-580213851

__Additional context__

https://forum.camunda.org/t/linter-plugin-error-element-has-disallowed-type-bpmn-inclusivegateway/23320

### PR DESCRIPTION
**Pull request by barmac**
Related to #41
Closes #44

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/.github/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by barmac** [comment]
The build failed on Node 15 even though I have not changed code.

**Comment by pinussilvestrus** [comment]
Interesting that it is failing because of one single new line, cf. https://travis-ci.com/github/bpmn-io/bpmnlint/jobs/404323815#L550

**actual**

```text
\n\n/home/travis/build/bpmn-io/bpmnlint/test/integration/cli/diagram-broken.bpmn\n    error  Parse error: failed to parse document as <bpmn:Definitions>\n\n✖ 1 problem (1 error, 0 warnings)\n\n
```

**expect**

```text
\n\n/home/travis/build/bpmn-io/bpmnlint/test/integration/cli/diagram-broken.bpmn\n    error  Parse error: failed to parse document as <bpmn:Definitions>\n\n✖ 1 problem (1 error, 0 warnings)\n
```

See the additional newline at the end.

**Comment by nikku** [comment]
Long story short, we should fix our CI builds to not use _latest_ Node as too many magic things can happen with pre-stable node versions (i.e. 11, 13, 15, ...).

**Comment by barmac** [comment]
Thanks. How do you like the PR?

**Comment by nikku** [comment]
Generally, as this is a matter of style, we do not provide rationale for these rules, similar to how I thought eslint does it.

In some cases however, eslint provides strong rationale for why something should not be done, example: https://eslint.org/docs/rules/for-direction#rule-details

**Comment by barmac** [comment]
I think that as long as rules don't lead to confusion on forums/issues, it's OK to assume they are self-explanatory. In this case, however, there has been a GitHub issue and a forum post questioning rule's existence.

**Review by nikku — APPROVED** [review]

**Pull request merged**
